const menu = [
  {
    id: 1,
    title: 'yummy stuff',
    category: 'breakfast',
    price: 5.99,
    img: './images/item-1.jpg',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum totam nesciunt aspernatur possimus laborum vel iste aut fugiat fuga necessitatibus. `,
  },
  {
    id: 2,
    title: 'healthy meal',
    category: 'lunch',
    price: 2.99,
    img: './images/item-2.jpg',
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda labore ea consequuntur voluptate sequi voluptatibus dolores aliquam tempore dolorum pariatur.`,
  },
  {
    id: 3,
    title: 'food of gods',
    category: 'lunch',
    price: 3.99,
    img: './images/item-3.jpg',
    desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem corporis vero ut repellat provident qui sapiente consectetur possimus quasi magni.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 5.99,
    img: './images/item-4.jpg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Id modi perspiciatis culpa, animi voluptatem velit corporis! Tempore omnis non atque! `,
  },
  {
    id: 5,
    title: 'vitamin attack',
    category: 'lunch',
    price: 4.99,
    img: './images/item-5.jpg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi vitae modi dolorem repudiandae quis quaerat eveniet explicabo nam nostrum perspiciatis! `,
  },
  {
    id: 6,
    title: 'natural dream',
    category: 'lunch',
    price: 8.99,
    img: './images/item-6.jpg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod laudantium fugiat dolore, rem ullam voluptatibus temporibus autem dolores sint corrupti?`,
  },
  {
    id: 7,
    title: 'beans overflow',
    category: 'breakfast',
    price: 5.99,
    img: './images/item-7.jpg',
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus rerum quisquam beatae, nobis ducimus dolorem similique consectetur asperiores sapiente numquam. `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'shakes',
    price: 2.99,
    img: './images/item-8.jpg',
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi alias nulla dicta illum sapiente accusamus velit cum repudiandae fugiat voluptatum! `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 3.99,
    img: './images/item-9.jpg',
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sapiente rem temporibus et odit minus a eligendi hic quia, tempore cum!`,
  },
];

export default menu;
